// Generated by CoffeeScript 1.6.3
(function() {
  var conversionRate, elt, elts, textNode, _i, _len;

  conversionRate = 7.5;

  Number.prototype.formatNumber = function() {
    var natural, parts, regexp;
    parts = String(this).split('.');
    natural = parts[0];
    regexp = new RegExp('(\\d{1})((\\d{3}( |$))+)', 'g');
    while (natural.match(regexp)) {
      natural = natural.replace(regexp, '$1 $2');
    }
    if (typeof parts[1] !== 'undefined') {
      return natural + ',' + parts[1];
    } else {
      return natural;
    }
  };

  String.prototype.convertCurrency = function() {
    return this.replace(/([\d][\d ,\.]*) ?Lt/g, function(match, p1) {
      var num;
      num = p1.replace(/( )/g, '');
      num = num.replace(/,/g, '.');
      num = parseInt(num);
      num *= conversionRate;
      num = num.formatNumber();
      return String(num) + ' Kč';
    });
  };

  Object.prototype.getTextNode = function() {
    var node, _i, _len, _ref;
    if (typeof this.childNodes === 'undefined' || !this.childNodes.length) {
      return null;
    }
    _ref = this.childNodes;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      node = _ref[_i];
      if (node.nodeName === '#text') {
        return node;
      }
    }
    return null;
  };

  elts = document.getElementsByTagName('*');

  for (_i = 0, _len = elts.length; _i < _len; _i++) {
    elt = elts[_i];
    textNode = elt.getTextNode();
    if (!textNode) {
      continue;
    }
    textNode.textContent = textNode.textContent.convertCurrency();
  }

}).call(this);
